[pkg]
name        = "zellij"
type        = "static"
description = "A terminal workspace with batteries included"
homepage    = ["https://zellij.dev"]
license     = ["MIT"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]
category    = ["ConsoleOnly", "TerminalEmulator", "System"]
repology    = ["zellij"]
provides    = ["zellij"]

[host]
supported = ["x86_64-linux", "aarch64-linux"]

[update]
strategy     = "github-releases"
repo         = "zellij-org/zellij"
strip-prefix = "v"

[source]
url     = "https://github.com/zellij-org/zellij/releases/download/v${version}/zellij-${arch}-unknown-linux-musl.tar.gz"

[source.install]
"zellij" = "zellij"

[[extra]]
url = "https://raw.githubusercontent.com/zellij-org/zellij/main/LICENSE.md"
to  = "LICENSE"
