[pkg]
name        = "namida"
type        = "appimage"
description = "TODO: one-line description"
homepage    = ["https://github.com/pkgforge-dev/Namida-AppImage"]
license     = ["TODO"]
maintainer  = ["TODO <you@example.com>"]
category    = ["TODO"]
repology    = ["TODO"]

[host]
supported = ["x86_64-linux", "aarch64-linux"]

[update]
strategy = "github-releases"
repo     = "pkgforge-dev/Namida-AppImage"
tag-suffix = "strip"

[source]
github = "pkgforge-dev/Namida-AppImage"
glob   = "*${arch}*.appimage"
