[pkg]
name        = "daggerfall-unity"
type        = "appimage"
description = "Open source recreation of Daggerfall in the Unity engine"
homepage    = [
  "https://www.dfworkshop.net",
  "https://github.com/Interkarma/daggerfall-unity",
]
license    = ["MIT"]
maintainer = ["QaidVoid (contact@qaidvoid.dev)"]
category   = ["Game", "RolePlaying", "AdventureGame"]
repology   = ["daggerfall-unity"]
provides   = ["daggerfall-unity"]

[host]
supported = ["x86_64-linux"]

[update]
strategy   = "github-releases"
repo       = "pkgforge-dev/Daggerfall-Unity-AppImage"
tag-suffix = "strip"

[source]
github = "pkgforge-dev/Daggerfall-Unity-AppImage"
glob   = "*${arch}*.appimage"

[[extra]]
url = "https://raw.githubusercontent.com/Interkarma/daggerfall-unity/master/LICENSE"
to  = "LICENSE"
verify = false
