[pkg]
name        = "mcfly"
type        = "static"
description = "Fly through your shell history"
homepage    = ["https://github.com/cantino/mcfly"]
license     = ["MIT"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]
category    = ["ConsoleOnly", "Utility"]
repology    = ["mcfly"]
provides    = ["mcfly"]

[host]
supported = ["x86_64-linux", "aarch64-linux"]

[update]
strategy     = "github-releases"
repo         = "cantino/mcfly"
strip-prefix = "v"

[source]
url     = "https://github.com/cantino/mcfly/releases/download/v${version}/mcfly-v${version}-${arch}-unknown-linux-musl.tar.gz"

[source.install]
"mcfly" = "mcfly"

[[extra]]
url = "https://raw.githubusercontent.com/cantino/mcfly/master/LICENSE"
to  = "LICENSE"
