[pkg]
name        = "croc"
type        = "static"
description = "Easily and securely send things from one computer to another"
homepage    = ["https://schollz.com/software/croc6"]
license     = ["MIT"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]
category    = ["FileTransfer", "Network", "Utility"]
repology    = ["croc"]

[host]
supported = ["x86_64-linux", "aarch64-linux", "riscv64-linux"]

[arch]
aarch64 = "ARM64"
x86_64  = "64bit"
riscv64 = "RISCV64"

[update]
strategy     = "github-releases"
repo         = "schollz/croc"
strip-prefix = "v"

[source]
github  = "schollz/croc"
glob    = "*Linux-${arch}.tar.gz"

[source.install]
"LICENSE" = "LICENSE"
"croc"    = "bin/croc"
