[pkg]
name        = "zenity-gtk3"
type        = "appimage"
description = "Display graphical dialog boxes from shell scripts (GTK3 version)"
homepage    = ["https://gitlab.gnome.org/GNOME/zenity"]
license     = ["LGPL-2.1"]
maintainer  = ["Samueru-sama (github.com/Samueru-sama)"]
category    = ["Development", "Utility"]
repology    = ["zenity"]
provides    = ["zenity-gtk3==zenity"]

[host]
supported = ["x86_64-linux", "aarch64-linux"]

[update]
strategy   = "github-releases"
repo       = "pkgforge-dev/Zenity-GTK3-AppImage"
tag-suffix = "strip"

[source]
github = "pkgforge-dev/Zenity-GTK3-AppImage"
glob   = "*${arch}*.appimage"

[[extra]]
url = "https://gitlab.gnome.org/GNOME/zenity/-/raw/master/COPYING"
to  = "LICENSE"
