[pkg]
name        = "tealdeer"
type        = "static"
description = "Very fast implementation of tldr in Rust"
homepage    = ["https://github.com/dbrgn/tealdeer"]
license     = ["Apache-2.0"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]
category    = ["ConsoleOnly", "Utility"]
repology    = ["tealdeer"]
provides    = ["tldr"]

[host]
supported = ["x86_64-linux", "aarch64-linux"]

[update]
strategy     = "github-releases"
repo         = "dbrgn/tealdeer"
strip-prefix = "v"

[source]
url = "https://github.com/dbrgn/tealdeer/releases/download/v${version}/tealdeer-linux-${arch}-musl"

[[extra]]
url = "https://github.com/dbrgn/tealdeer/releases/download/v${version}/LICENSE-APACHE.txt"
to  = "LICENSE"
