#!/SBUILD ver @v0.4.5    
#SELF:
_disabled: false

pkg: "gdm-settings"
pkg_id: ""
pkg_type: "appimage"
build_util:
  - "7z"
  - "curl"
  - "eget"
  - "jq"
  - "rsync"
  - "squishy-cli"
  - "wget"
category:
  - ""
description: " A settings app for GNOME's Login Manager, GDM."
distro_pkg:
  alpine:
    - ""
  archlinux:
    aur:
      - ""
  deb:
    - ""    
  nixpkgs:
    - ""
homepage:
  - ""
license:
  - ""
maintainer:
  - "Azathothas (https://github.com/Azathothas)"
note:
 - ""
repology:
 - "gdm-settings"
src_url:
  - "https://github.com/gdm-settings/gdm-settingsgdm-settings/gdm-settings"
tag:
  - ""
x_exec:
  shell: bash
  run: |
    {doodly-doooo}
