#!/SBUILD ver @v0.4.5    
#SELF:
_disabled: false

pkg: "openapi-tui"
pkg_id: ""
pkg_type: "appimage"
build_util:
  - "7z"
  - "curl"
  - "eget"
  - "jq"
  - "rsync"
  - "squishy-cli"
  - "wget"
category:
  - ""
description: " Terminal UI to list, browse and run APIs defined with openapi spec."
distro_pkg:
  alpine:
    - ""
  archlinux:
    aur:
      - ""
  deb:
    - ""    
  nixpkgs:
    - ""
homepage:
  - ""
license:
  - ""
maintainer:
  - "Azathothas (https://github.com/Azathothas)"
note:
 - ""
repology:
 - "openapi-tui"
src_url:
  - "https://github.com/zaghaghi/openapi-tuizaghaghi/openapi-tui"
tag:
  - ""
x_exec:
  shell: bash
  run: |
    {doodly-doooo}
