#!/SBUILD ver @v1.0.0    
#SELF:
_disabled: false

pkg: "rabix-composer"
pkg_id: ""
pkg_type: "appimage"
build_util:
  - "7z"
  - "curl"
  - "eget"
  - "jq"
  - "rsync"
  - "squishy-cli"
  - "wget"
category:
  - ""
description: " Rabix Composer is a desktop IDE for working with Common Workflow Language"
distro_pkg:
  alpine:
    - ""
  archlinux:
    aur:
      - ""
  deb:
    - ""    
  nixpkgs:
    - ""
homepage:
  - ""
license:
  - ""
maintainer:
  - "Azathothas (https://github.com/Azathothas)"
note:
 - ""
repology:
 - "rabix-composer"
src_url:
  - "https://github.com/rabix/composerrabix/composer"
tag:
  - ""
x_exec:
  shell: bash
  run: |
    {doodly-doooo}
