[pkg]
name        = "kolourpaint"
type        = "appimage"
description = "Easy-to-use paint program for KDE"
homepage    = [
  "https://apps.kde.org/kolourpaint",
  "https://invent.kde.org/graphics/kolourpaint",
]
license    = ["BSD-2-Clause", "LGPL-2.0-or-later"]
maintainer = ["QaidVoid (contact@qaidvoid.dev)"]
category   = ["Graphics", "RasterGraphics", "2DGraphics"]
repology   = ["kolourpaint"]

[host]
supported = ["x86_64-linux", "aarch64-linux"]

[update]
strategy   = "github-releases"
repo       = "pkgforge-dev/KolourPaint-AppImage"
tag-suffix = "strip"

[source]
github = "pkgforge-dev/KolourPaint-AppImage"
glob   = "*${arch}*.appimage"

[[extra]]
url = "https://invent.kde.org/graphics/kolourpaint/-/raw/master/LICENSES/BSD-2-Clause.txt"
to  = "LICENSE"
verify = false
