[pkg]
name        = "alist"
type        = "static"
description = "A file list/WebDAV program that supports multiple storages"
src         = ["https://github.com/alist-org/alist"]
homepage    = ["https://alistgo.com"]
license     = ["AGPL-3.0-or-later"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]
category    = ["FileManager", "Network"]
repology    = ["alist"]

[host]
supported = ["x86_64-linux", "aarch64-linux", "riscv64-linux"]

[arch]
aarch64 = "arm64"
x86_64  = "amd64"

[update]
strategy   = "github-releases"
repo       = "pkgforge/builds"
tag-prefix = "alist-"

[source]

[source.url]
x86_64-linux  = "https://github.com/AlistGo/alist/releases/download/v${version}/alist-linux-musl-${arch}.tar.gz"
aarch64-linux = "https://github.com/AlistGo/alist/releases/download/v${version}/alist-linux-musl-${arch}.tar.gz"
riscv64-linux = "https://github.com/pkgforge/builds/releases/download/alist-${version}/alist-${version}-riscv64-linux.tar.gz"

[source.install]
"alist" = "bin/alist"

[[extra]]
url = "https://raw.githubusercontent.com/AlistGo/alist/main/LICENSE"
to  = "LICENSE"
verify = false
