[pkg]
name        = "sview"
type        = "appimage"
description = "Media player for 3D/2D content"
homepage    = ["https://www.sview.ru", "https://github.com/pkgforge-dev/sView-AppImage"]
license     = ["GPL-3.0"]
maintainer  = ["Samueru-sama (github.com/Samueru-sama)"]
category    = ["AudioVideo", "Player"]
repology    = ["sview"]
channel     = "unstable"

[host]
supported = ["x86_64-linux"]

[update]
strategy   = "github-releases"
repo       = "pkgforge-dev/sView-AppImage"
tag-suffix = "strip"

[source]
github = "pkgforge-dev/sView-AppImage"
glob   = "*${arch}*.appimage"

[[extra]]
url = "https://raw.githubusercontent.com/gkv311/sview/refs/heads/master/LICENSE_GPL_3-0.txt"
to  = "LICENSE"
verify = false
