[pkg]
name        = "gram"
type        = "appimage"
description = "Code editor forked from Zed, without AI or subscriptions"
homepage    = ["https://codeberg.org/GramEditor/gram"]
license     = ["GPL-3.0"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]
category    = ["Development", "TextEditor", "IDE"]
repology    = ["gram"]

[host]
supported = ["x86_64-linux", "aarch64-linux"]

[update]
strategy   = "github-releases"
repo       = "pkgforge-dev/Gram-AppImage-Enhanced"
tag-suffix = "strip"

[source]
github = "pkgforge-dev/Gram-AppImage-Enhanced"
glob   = "*${arch}*.appimage"

[[extra]]
url = "https://codeberg.org/GramEditor/gram/raw/branch/main/LICENSE-GPL"
to  = "LICENSE"
verify = false
