[pkg]
name        = "speedcrunch"
type        = "appimage"
description = "Fast and precise calculator"
homepage    = ["https://speedcrunch.org"]
license     = ["GPL-2.0"]
maintainer  = ["Samueru-sama (github.com/Samueru-sama)"]
category    = ["Calculator", "Utility"]
repology    = ["speedcrunch"]
provides    = ["speedcrunch"]

[host]
supported = ["x86_64-linux"]

[update]
strategy   = "github-releases"
repo       = "pkgforge-dev/SpeedCrunch-AppImage"
tag-suffix = "strip"

[source]
github = "pkgforge-dev/SpeedCrunch-AppImage"
glob   = "*${arch}*.appimage"

[[extra]]
url = "https://bitbucket.org/heldercorreia/speedcrunch/raw/3c1b4c18ccb275eb2891f9d8ff36a9205c0f566b/LICENSE"
to  = "LICENSE"
verify = false
