[pkg]
name        = "itgmania"
type        = "appimage"
description = "A free, open source, and community-driven dance game"
homepage    = ["https://www.itgmania.com/", "https://github.com/itgmania/itgmania"]
license     = ["GPL-3.0"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]
category    = ["Game", "ArcadeGame", "Music"]
repology    = ["itgmania"]
provides    = ["itgmania"]

[host]
supported = ["x86_64-linux", "aarch64-linux"]

[update]
strategy   = "github-releases"
repo       = "pkgforge-dev/ITGmania-AppImage"
tag-suffix = "strip"

[source]
github = "pkgforge-dev/ITGmania-AppImage"
glob   = "*${arch}*.appimage"

[[extra]]
url = "https://raw.githubusercontent.com/itgmania/itgmania/release/LICENSE"
to  = "LICENSE"
verify = false
